module.exports = {
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  cursorOffset: -1,
  embeddedLanguageFormatting: "auto",
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "css",
  insertPragma: false,
  jsxSingleQuote: false,
  pluginSearchDirs: [],
  plugins: [],
  printWidth: 80,
  proseWrap: "preserve",
  quoteProps: "consistent",
  rangeEnd: Infinity,
  rangeStart: 0,
  requirePragma: false,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  useTabs: false,
};
