on:
  workflow_call:
    inputs:
      task:
        description: "Task to run"
        required: true
        default: "news"
        type: string
      link:
        description: "Link"
        required: false
        type: string

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: OSRS Web Scraper
        run: npm run start:node ${{ inputs.task }} "${{ inputs.link }}"

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.task }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: out/${{ inputs.task }}/
