name: Pull Request

on:
  pull_request:

jobs:
  test_for_changeset:
    runs-on: ubuntu-latest
    if: github.head_ref != 'changeset-release/main'
    name: Test for presence of new Changeset files
    steps:
      - uses: actions/checkout@v4

      - name: Get .changeset changes
        id: changeset-files
        uses: tj-actions/changed-files@v46
        with:
          files: .changeset/*.md

      - name: Check for added files
        id: changeset-check-added
        run: |
          echo "Valid PRs must have a new changeset file."
          test -n "${{ steps.changeset-files.outputs.added_files }}"

  lint_build_test:
    name: "Lint, Built, & Test"
    uses: ./.github/workflows/action-lint-build-test.yml
