name: Push Main

on:
  push:
    branches:
      - main

jobs:
  lint_build_test:
    name: "Lint, Built, & Test"
    uses: ./.github/workflows/action-lint-build-test.yml
    secrets: inherit

  changeset:
    needs: lint_build_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git config
        run: git config --global url."https://".insteadOf git://

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          cache: npm
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create Release Pull Request or Release
        id: changeset
        uses: changesets/action@v1
        with:
          publish: echo Release && echo "New tag:"
          title: Release
          commit: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
