name: Run OSRS Web Scraper

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Task to run"
        required: true
        default: "news"
        type: choice
        options:
          - news
          - poll
          - worlds
      link:
        description: "Link"
        required: false

jobs:
  run-scraper:
    name: "Run OSRS Web Scraper"
    uses: ./.github/workflows/action-run-scraper.yml
    with:
      task: ${{ github.event.inputs.task }}
      link: ${{ github.event.inputs.link }}
