name: Run News Scraper

on:
  workflow_dispatch:
    inputs:
      newsLink:
        description: "News Link"
        required: false

      pollLink:
        description: "Poll Link"
        required: false

jobs:
  scrapeNews:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Scrape News Post
        run: export NEWS_LINK=${{ github.event.inputs.newsLink }} && export POLL_LINK=${{ github.event.inputs.pollLink }} && yarn start:node

      - name: Upload News Results
        if: "${{ github.event.inputs.newsLink != '' }}"
        uses: actions/upload-artifact@v3
        with:
          name: newspost-${{ github.run_id }}-${{ github.run_attempt }}
          path: out/news/

      - name: Upload Poll Results
        if: "${{ github.event.inputs.pollLink != '' }}"
        uses: actions/upload-artifact@v3
        with:
          name: poll-${{ github.run_id }}-${{ github.run_attempt }}
          path: out/polls/
